import torch
from torch import nn
from typing import Literal, Union

from ..schema import FeatureSchema
from ..ML_models._base_save_load import _ArchitectureBuilder

from .._core import get_logger
from ..keys._keys import MLTaskKeys, SchemaKeys


_LOGGER = get_logger("Sequence LSTM")


__all__ = [
    "DragonSequenceLSTM"
]

# References:
# Orthogonal initialization: "Exact solutions to the nonlinear dynamics of learning in deep linear neural networks" (Saxe et al., 2013) https://arxiv.org/abs/1312.6120
# Glorot initialization: "Understanding the difficulty of training deep feedforward neural networks" (Glorot et al., 2010) https://proceedings.mlr.press/v9/glorot10a.html

class DragonSequenceLSTM(_ArchitectureBuilder):
    """
    An LSTM-based network for multivariate sequence prediction tasks.
    
    Dynamically constructs separate prediction heads for continuous and categorical 
    targets based on the provided FeatureSchema.
    """
    def __init__(self, 
                 schema: FeatureSchema,
                 targets: list[str],
                 prediction_mode: Union[Literal["autoregressive-sequence-to-sequence", 
                                                "autoregressive-sequence-to-value", 
                                                "exogenous-sequence-to-sequence", 
                                                "exogenous-sequence-to-value"], str],
                 sequence_length: int,
                 hidden_size: int = 100,
                 recurrent_layers: int = 2,
                 dropout: float = 0.1):
        """
        Initializes the multi-head LSTM for multivariate sequence prediction.

        Args:
            schema (FeatureSchema): The definitive schema containing feature names, data types, 
                and categorical cardinality configurations.
            targets (list[str]): A list of column names indicating the target variables to predict.
            prediction_mode (str): Determines the temporal structure of the outputs.
                - 'autoregressive': Includes target variables in the input sequence for rolling predictions.
                - 'exogenous': Excludes target variables from the input sequence, relying solely on exogenous features.
                - 'sequence-to-sequence': Predicts a full sequence matching the input time steps.
                - 'sequence-to-value': Predicts single values corresponding to the final time step.
            sequence_length (int): The exact length of the sliding windows generated by the dataset.
            hidden_size (int): The number of features in the LSTM's hidden state
            recurrent_layers (int): The number of recurrent LSTM layers.
            dropout (float): The dropout probability for all but the last LSTM layer.
            
        ### Note:
        The LSTM will be bidirectional for any prediction mode except autoregressive sequence-to-sequence to prevent information leakage (look-ahead). 
        Autoregressive sequence-to-value safely allows bidirectional processing because it predicts a single future value beyond the input window. 
        Since the future target is not present at any time step within the historical input sequence, 
        evaluating the window bidirectionally does not expose the model to the answer key.
        """
        super().__init__()

        # --- 1. Validation ---
        if prediction_mode not in MLTaskKeys.ALL_SEQUENCE_TASKS:
            _LOGGER.error(f"Unrecognized prediction mode: '{prediction_mode}'.")
            raise ValueError()
            
        if not targets:
            _LOGGER.error("The 'targets' list cannot be empty.")
            raise ValueError()

        if not isinstance(hidden_size, int) or hidden_size < 1:
            _LOGGER.error("hidden_size must be a positive integer.")
            raise ValueError()

        if not isinstance(recurrent_layers, int) or recurrent_layers < 1:
            _LOGGER.error("recurrent_layers must be a positive integer.")
            raise ValueError()

        if not (0.0 <= dropout < 1.0):
            _LOGGER.error("dropout must be a float between 0.0 and 1.0.")
            raise ValueError()
        
        # Internal bidirectional logic: prevent leakage in autoregressive seq-to-seq
        self.bidirectional = (prediction_mode != MLTaskKeys.AUTOREGRESSIVE_SEQUENCE_SEQUENCE)

        # --- 2. Save configuration for _ArchitectureBuilder ---
        self.model_hparams = {
            SchemaKeys.SCHEMA_DICT: schema.to_dict(),
            'targets': targets,
            'prediction_mode': prediction_mode,
            'sequence_length': sequence_length,
            'hidden_size': hidden_size,
            'recurrent_layers': recurrent_layers,
            'dropout': dropout
        }

        self.prediction_mode = prediction_mode
        self.targets = targets
        self.sequence_length = sequence_length
        
        # Adjust input features for exogenous modes
        if prediction_mode in [MLTaskKeys.EXOGENOUS_SEQUENCE_SEQUENCE, MLTaskKeys.EXOGENOUS_SEQUENCE_VALUE]:
            self.in_features = schema.number_of_features - len(targets)
        else: # autoregressive modes
            self.in_features = schema.number_of_features
            
        self.hidden_size = hidden_size
        self.recurrent_layers = recurrent_layers
        self.dropout = dropout

        # --- 3. LSTM Backbone ---
        # Unrolling the LSTM layers to inject Layer Normalization between them
        self.lstm_layers = nn.ModuleList()
        self.layer_norms = nn.ModuleList()
        
        current_in_features = self.in_features
        for i in range(recurrent_layers):
            lstm_layer = nn.LSTM(
                input_size=current_in_features,
                hidden_size=hidden_size,
                num_layers=1,
                bidirectional=self.bidirectional,
                batch_first=True
            )
            
            # Apply orthogonal initialization to hidden-to-hidden weights
            for name, param in lstm_layer.named_parameters():
                if 'weight_hh' in name:
                    nn.init.orthogonal_(param)
                elif 'weight_ih' in name:
                    nn.init.xavier_uniform_(param)
                elif 'bias' in name:
                    nn.init.zeros_(param)
                    
            self.lstm_layers.append(lstm_layer)
            
            # Dimension calculation for LayerNorm and next layer input
            num_directions = 2 if self.bidirectional else 1
            out_features = hidden_size * num_directions
            
            # LayerNorm not needed after the very last recurrent layer
            if i < recurrent_layers - 1:
                self.layer_norms.append(nn.LayerNorm(out_features))
                
            current_in_features = out_features

        self.dropout_layer = nn.Dropout(dropout) if dropout > 0.0 else nn.Identity()
        
        # Calculate dimension feeding into head projections
        head_in_features = current_in_features

        # --- 4. Multi-Head Outputs ---
        self.target_heads = nn.ModuleDict()

        for target in targets:
            if target in schema.categorical_feature_names:
                target_idx = schema.feature_names.index(target)
                if schema.categorical_index_map and target_idx in schema.categorical_index_map:
                    cardinality = schema.categorical_index_map[target_idx]
                else:
                    _LOGGER.warning(f"Cardinality for categorical target '{target}' not found. Defaulting to 2.")
                    cardinality = 2

                self.target_heads[target] = nn.Linear(head_in_features, cardinality)
            else:
                self.target_heads[target] = nn.Linear(head_in_features, 1)

    @property
    def _is_seq_to_val(self) -> bool:
        return self.prediction_mode in [MLTaskKeys.AUTOREGRESSIVE_SEQUENCE_VALUE, MLTaskKeys.EXOGENOUS_SEQUENCE_VALUE]

    @property
    def _is_seq_to_seq(self) -> bool:
        return self.prediction_mode in [MLTaskKeys.AUTOREGRESSIVE_SEQUENCE_SEQUENCE, MLTaskKeys.EXOGENOUS_SEQUENCE_SEQUENCE]

    def forward(self, x: torch.Tensor) -> dict[str, torch.Tensor]:
        """
        Defines the forward pass.

        Args:
            x (torch.Tensor): Input tensor of shape (batch_size, sequence_length, features)
                              or (batch_size, sequence_length).

        Returns:
            dict[str, torch.Tensor]: A dictionary mapping each target name to its prediction tensor.
        """
        # --- Handle Input Shape ---
        if x.ndim == 2:
            x = x.unsqueeze(-1)

        # --- Route through unrolled LSTM layers ---
        current_out = x
        for i, lstm in enumerate(self.lstm_layers):
            current_out, _ = lstm(current_out)
            
            # Apply Layer Normalization and Dropout between recurrent layers
            if i < len(self.layer_norms):
                current_out = self.layer_norms[i](current_out)
                current_out = self.dropout_layer(current_out)

        lstm_out = current_out

        # --- Route through Multi-Heads ---
        predictions = {}

        if self._is_seq_to_val:
            last_step = lstm_out[:, -1, :]

            for target_name, head in self.target_heads.items():
                out = head(last_step)
                predictions[target_name] = out.squeeze(-1) if out.shape[-1] == 1 else out

        elif self._is_seq_to_seq:
            for target_name, head in self.target_heads.items():
                out = head(lstm_out)
                predictions[target_name] = out.squeeze(-1) if out.shape[-1] == 1 else out

        return predictions

    def get_architecture_config(self) -> dict:
        """Returns the configuration of the model for serialization."""
        return self.model_hparams

    def extra_repr(self) -> str:
        """Provides high-level architecture details for print() and PyTorch inspection."""
        return (
            f"prediction_mode='{self.prediction_mode}', "
            f"targets={len(self.targets)}, "
            f"sequence_length={self.sequence_length}, "
            f"in_features={self.in_features}, "
            f"hidden_size={self.hidden_size}, "
            f"recurrent_layers={self.recurrent_layers}, "
            f"bidirectional={self.bidirectional}, "
            f"dropout={self.dropout}"
        )

    def _get_finetune_components(self) -> dict[str, nn.Module]:
        """Maps LSTM sequence model layers for the DragonFinetuner."""
        return {
            "backbone": nn.ModuleList([self.lstm_layers, self.layer_norms]),
            "heads": self.target_heads
        }
