from ._keys import PyTorchLogKeys, PyTorchCheckpointKeys, MLTaskKeys, PyTorchInferenceKeys, ObjectDetectionKeys


class CheckpointKeys:
    """Checkpoint callback keys."""
    TRAIN_LOSS = PyTorchLogKeys.TRAIN_LOSS
    VALIDATION_LOSS = PyTorchLogKeys.VAL_LOSS
    

class FinalizedFileKeys:
    """Keys for finalized model files."""
    MODEL_WEIGHTS = PyTorchCheckpointKeys.MODEL_STATE
    EPOCH = PyTorchCheckpointKeys.EPOCH
    TASK = PyTorchCheckpointKeys.TASK
    CLASSIFICATION_THRESHOLD = PyTorchCheckpointKeys.CLASSIFICATION_THRESHOLD
    CLASS_MAP = PyTorchCheckpointKeys.CLASS_MAP
    SEQUENCE_LENGTH = PyTorchCheckpointKeys.SEQUENCE_LENGTH
    INITIAL_SEQUENCE = PyTorchCheckpointKeys.INITIAL_SEQUENCE
    TARGET_NAME = PyTorchCheckpointKeys.TARGET_NAME
    TARGET_NAMES = PyTorchCheckpointKeys.TARGET_NAMES
    TARGET_TYPES = PyTorchCheckpointKeys.TARGET_TYPES
    

class TaskKeys:
    """
    Task keys used in the Dragon ML pipeline:
    
    1. REGRESSION
    2. MULTITARGET_REGRESSION
    3. BINARY_CLASSIFICATION
    4. MULTICLASS_CLASSIFICATION
    5. MULTILABEL_BINARY_CLASSIFICATION
    6. BINARY_IMAGE_CLASSIFICATION
    7. MULTICLASS_IMAGE_CLASSIFICATION  
    8. BINARY_SEGMENTATION
    9. MULTICLASS_SEGMENTATION
    10. OBJECT_DETECTION
    11. AUTOREGRESSIVE_SEQUENCE_SEQUENCE
    12. AUTOREGRESSIVE_SEQUENCE_VALUE
    13. EXOGENOUS_SEQUENCE_SEQUENCE
    14. EXOGENOUS_SEQUENCE_VALUE
    15. DIFFUSION
    16. AUTOENCODER
    """
    REGRESSION = MLTaskKeys.REGRESSION
    MULTITARGET_REGRESSION = MLTaskKeys.MULTITARGET_REGRESSION
    BINARY_CLASSIFICATION = MLTaskKeys.BINARY_CLASSIFICATION
    MULTICLASS_CLASSIFICATION = MLTaskKeys.MULTICLASS_CLASSIFICATION
    MULTILABEL_BINARY_CLASSIFICATION = MLTaskKeys.MULTILABEL_BINARY_CLASSIFICATION
    BINARY_IMAGE_CLASSIFICATION = MLTaskKeys.BINARY_IMAGE_CLASSIFICATION
    MULTICLASS_IMAGE_CLASSIFICATION = MLTaskKeys.MULTICLASS_IMAGE_CLASSIFICATION
    BINARY_SEGMENTATION = MLTaskKeys.BINARY_SEGMENTATION
    MULTICLASS_SEGMENTATION = MLTaskKeys.MULTICLASS_SEGMENTATION
    OBJECT_DETECTION = MLTaskKeys.OBJECT_DETECTION
    AUTOREGRESSIVE_SEQUENCE_SEQUENCE = MLTaskKeys.AUTOREGRESSIVE_SEQUENCE_SEQUENCE
    AUTOREGRESSIVE_SEQUENCE_VALUE = MLTaskKeys.AUTOREGRESSIVE_SEQUENCE_VALUE
    EXOGENOUS_SEQUENCE_SEQUENCE = MLTaskKeys.EXOGENOUS_SEQUENCE_SEQUENCE
    EXOGENOUS_SEQUENCE_VALUE = MLTaskKeys.EXOGENOUS_SEQUENCE_VALUE
    DIFFUSION = MLTaskKeys.DIFFUSION
    AUTOENCODER = MLTaskKeys.AUTOENCODER

class InferenceKeys:
    # For regression tasks
    PREDICTIONS = PyTorchInferenceKeys.PREDICTIONS
    
    # For distribution regression tasks
    VARIANCE = PyTorchInferenceKeys.VARIANCE
    
    # For classification / vision tasks
    LABELS = PyTorchInferenceKeys.LABELS
    PROBABILITIES = PyTorchInferenceKeys.PROBABILITIES
    LABEL_NAMES = PyTorchInferenceKeys.LABEL_NAMES
    
    #For object detection tasks
    BOXES = ObjectDetectionKeys.BOXES
    SCORES = ObjectDetectionKeys.SCORES
    