import numpy as np
from PIL import Image
from pathlib import Path
import re
from collections import defaultdict
from typing import Union, Literal

from .._core import get_logger
from ..path_manager import make_fullpath


_LOGGER = get_logger("Mask Annotation")


__all__ = [
    "merge_masks",
    "merge_masks_with_inferred_class",
    "convert_masks_mode",
]


LABEL_STUDIO_PATTERN = re.compile(r"^(.*?)-tag-(.*?)(?:-\d+)?\.png$")


def _generate_color_palette() -> list[int]:
    """Generates a distinct color palette for P mode images (768 integers)."""
    palette = [0, 0, 0]  # Class 0: Black
    
    # Standard distinct colors for classes 1-20
    colors = [
        (230, 25, 75), (60, 180, 75), (255, 225, 25), (0, 130, 200), 
        (245, 130, 48), (145, 30, 180), (70, 240, 240), (240, 50, 230), 
        (210, 245, 60), (250, 190, 212), (0, 128, 128), (220, 190, 255), 
        (170, 110, 40), (255, 250, 200), (128, 0, 0), (170, 255, 195), 
        (128, 128, 0), (255, 215, 180), (0, 0, 128), (128, 128, 128)
    ]
    for r, g, b in colors:
        palette.extend([r, g, b])
        
    # Pad the rest up to 256 colors * 3 channels = 768 values
    remaining_colors = 256 - (len(palette) // 3)
    for i in range(remaining_colors):
        palette.extend([i, i, i])
        
    return palette


def merge_masks(input_dir: Union[Path, str], 
                output_dir: Union[Path, str], 
                class_map: dict[str, int]) -> None:
    """
    Reads individual segmentation mask images from a directory, groups them by their base 
    task name, merges them into a single 2D array per task, and saves the output.
    
    The function uses a regular expression to parse filenames in the format 
    `<base_task>-tag-<label_name>[-<optional_index>].png`. 
    
    It processes each group of 
    images belonging to the same base task, assigning pixel values based on the provided 
    class_map. If a mask has multiple overlapping annotations, the last one processed 
    will overwrite the previous pixels.
    
    Args:
        input_dir (Path | str): The directory containing the individual label mask PNG files 
            generated by the annotation tool.
        output_dir (Path | str): The directory where the final merged mask PNG files 
            will be saved. It will be created if it does not exist.
        class_map (dict[str, int]): A dictionary mapping the string label names 
            (parsed from the filenames) to their corresponding integer class IDs 
            (e.g., {"Background": 0, "Voids": 1}).
    """
    input_path = make_fullpath(input_dir, make=False, enforce="directory")
    output_path = make_fullpath(output_dir, make=True, enforce="directory")
    
    input_files = list(input_path.glob("*.png"))
    if not input_files:
        _LOGGER.warning(f"Input directory is empty: {input_path}")
        return
        
    _LOGGER.info(f"Found {len(input_files)} images in the input directory.")
    
    grouped_tasks = defaultdict(lambda: defaultdict(list))
    pattern = LABEL_STUDIO_PATTERN
    
    for file_path in input_files:
        match = pattern.match(file_path.name)
        if match:
            grouped_tasks[match.group(1)][match.group(2)].append(file_path)
    
    for base_task, grouped_masks in grouped_tasks.items():
        first_path = next(iter(grouped_masks.values()))[0]
        image_shape = Image.open(first_path).size[::-1] 
    
        merged_mask = np.zeros(image_shape, dtype=np.uint8)
        
        for label_name, paths in grouped_masks.items():
            if label_name not in class_map:
                _LOGGER.warning(f"Label '{label_name}' is not in the class_map. Skipping.")
                continue
                
            class_id = class_map[label_name]
            for path in paths:
                mask_array = np.array(Image.open(path).convert("L"))
                merged_mask[mask_array > 127] = class_id
                
        current_output_path = output_path / f"{base_task}.png"
        
        out_img = Image.fromarray(merged_mask, mode="P")
        out_img.putpalette(_generate_color_palette())
        out_img.save(current_output_path)
        
    _LOGGER.info(f"Successfully saved {len(grouped_tasks)} merged output images.")
    

def merge_masks_with_inferred_class(
    input_dir: Union[Path, str], 
    output_dir: Union[Path, str], 
    class_map: dict[str, int], 
    inferred_class_name: str
) -> None:
    """
    Merges individual segmentation masks into a single image, initializing the base 
    canvas with an inferred class ID and carving out specific regions.
    
    The function uses a regular expression to parse filenames in the format 
    `<base_task>-tag-<label_name>[-<optional_index>].png`. 

    This function is designed for scenarios where the entire image should default to a 
    specific class (the inferred class), except for areas explicitly marked as 'Background' or other specific labels.
    It first fills the canvas with the inferred class ID, sets any areas defined in the 
    'Background' mask to 0 (black), and then applies the remaining label masks on top.

    Args:
        input_dir (Path | str): The directory containing the individual label mask PNG files 
            generated by the annotation tool.
        output_dir (Path | str): The directory where the final merged mask PNG files 
            will be saved. It will be created if it does not exist.
        class_map (dict[str, int]): A dictionary mapping the string label names 
            (parsed from the filenames) to their corresponding integer class IDs 
            (e.g., {"Background": 0, "Voids": 1}).
        inferred_class_name (str): The label name corresponding to the class that 
            should fill the initial canvas (must exist in the class_map).
    """
    if inferred_class_name not in class_map.keys():
        _LOGGER.error(f"Inferred class name '{inferred_class_name}' not found in class_map.")
        raise ValueError()
    
    input_path = make_fullpath(input_dir, make=False, enforce="directory")
    output_path = make_fullpath(output_dir, make=True, enforce="directory")
    
    input_files = list(input_path.glob("*.png"))
    if not input_files:
        _LOGGER.warning(f"Input directory is empty: {input_path}")
        return
        
    _LOGGER.info(f"Found {len(input_files)} images in the input directory.")
    
    grouped_tasks = defaultdict(lambda: defaultdict(list))
    pattern = LABEL_STUDIO_PATTERN
    
    for file_path in input_files:
        match = pattern.match(file_path.name)
        if match:
            grouped_tasks[match.group(1)][match.group(2)].append(file_path)
            
    for base_task, grouped_masks in grouped_tasks.items():
        bg_key = next((k for k in grouped_masks.keys() if k.lower() == "background"), None)
        if not bg_key:
            _LOGGER.error(f"No 'Background' label found for task '{base_task}'. A background mask is required to carve out the inferred class.")
            raise ValueError()

        first_path = next(iter(grouped_masks.values()))[0]
        image_shape = Image.open(first_path).size[::-1]
        
        inferred_class_id = class_map[inferred_class_name]
        merged_mask = np.full(image_shape, inferred_class_id, dtype=np.uint8)
        
        for path in grouped_masks[bg_key]:
            mask_array = np.array(Image.open(path).convert("L"))
            merged_mask[mask_array > 127] = 0
            
        for label_name, paths in grouped_masks.items():
            if label_name == bg_key:
                continue
            if label_name not in class_map:
                _LOGGER.warning(f"Label '{label_name}' not found in class_map. Skipping.")
                continue
                
            class_id = class_map[label_name]
            for path in paths:
                mask_array = np.array(Image.open(path).convert("L"))
                merged_mask[mask_array > 127] = class_id
                
        current_output_path = output_path / f"{base_task}.png"
        
        out_img = Image.fromarray(merged_mask, mode="P")
        out_img.putpalette(_generate_color_palette())
        out_img.save(current_output_path)
        
    _LOGGER.info(f"Successfully saved {len(grouped_tasks)} merged output images.")


def convert_masks_mode(
    input_dir: Union[str, Path],
    output_dir: Union[str, Path],
    convert_to: Literal["L", "P"],
    verbose: int = 2
) -> None:
    """
    Converts a directory of PNG segmentation masks to the specified image mode ("L" or "P").
    
    Safely handles the transition between Grayscale ("L") and Palette ("P") modes 
    by extracting the raw underlying integer data to prevent destructive color conversions.
    
    Args:
        input_dir (Union[str, Path]): Directory containing the input masks (PNG files).
        output_dir (Union[str, Path]): Directory to save the converted masks.
        convert_to (Literal["L", "P"]): The desired output image mode.
            - L: Grayscale (8-bit pixels, black and white)
            - P: Palette (8-bit pixels, mapped to a color palette)
        verbose (int): Verbosity level for logging.
    """
    if convert_to not in {"L", "P"}:
        _LOGGER.error(f"Invalid mode '{convert_to}'. Must be 'L' or 'P'.")
        raise ValueError()

    input_path = make_fullpath(input_dir, make=False, enforce="directory")
    output_path = make_fullpath(output_dir, make=True, enforce="directory")
    
    input_files = list(input_path.glob("*.png"))
    if not input_files:
        _LOGGER.error(f"Input directory is empty or contains no PNGs: {input_path}")
        return
    
    if verbose >= 3:
        _LOGGER.info(f"Found {len(input_files)} images to convert to mode '{convert_to}'.")
    
    palette = _generate_color_palette() if convert_to == "P" else None
    
    converted_count = 0
    invalid_conversions = []
    for file_path in input_files:
        try:
            with Image.open(file_path) as img:
                if img.mode not in {"L", "P"}:
                    if verbose >= 3:
                        _LOGGER.warning(f"File '{file_path.name}' is in mode '{img.mode}'. Attempting to extract raw array.")
                
                raw_array = np.array(img)
                out_img = Image.fromarray(raw_array, mode=convert_to)
                
                if convert_to == "P" and palette:
                    out_img.putpalette(palette)
                    
                out_img.save(output_path / file_path.name)
                converted_count += 1
        except Exception as e:
            if verbose >= 3:
                _LOGGER.warning(f"Failed to convert '{file_path.name}': {e}")
            invalid_conversions.append(file_path.name)
    
    if verbose >= 2:
        _LOGGER.info(f"Processed {converted_count} valid mask files in '{input_path}'.")
        
    if invalid_conversions and verbose >= 1:
        _LOGGER.warning(f"Skipped {len(invalid_conversions)} invalid files: {invalid_conversions}")
