import numpy as np
from PIL import Image
from pathlib import Path
import re
from collections import defaultdict
from typing import Union

from .._core import get_logger
from ..path_manager import make_fullpath


_LOGGER = get_logger("Mask Annotation")


__all__ = [
    "merge_masks",
    "merge_masks_with_inferred_class",
]


LABEL_STUDIO_PATTERN = re.compile(r"^(.*?)-tag-(.*?)(?:-\d+)?\.png$")


def merge_masks(input_dir: Union[Path, str], 
                output_dir: Union[Path, str], 
                class_map: dict[str, int]) -> None:
    """
    Reads individual segmentation mask images from a directory, groups them by their base 
    task name, merges them into a single 2D array per task, and saves the output.
    
    The function uses a regular expression to parse filenames in the format 
    '<base_task>-tag-<label_name>[-<optional_index>].png'. 
    
    It processes each group of 
    images belonging to the same base task, assigning pixel values based on the provided 
    class_map. If a mask has multiple overlapping annotations, the last one processed 
    will overwrite the previous pixels.
    
    Args:
        input_dir (Path | str): The directory containing the individual label mask PNG files 
            generated by the annotation tool.
        output_dir (Path | str): The directory where the final merged mask PNG files 
            will be saved. It will be created if it does not exist.
        class_map (dict[str, int]): A dictionary mapping the string label names 
            (parsed from the filenames) to their corresponding integer class IDs 
            (e.g., {"Background": 0, "Voids": 1}).
    """
    input_path = make_fullpath(input_dir, make=False, enforce="directory")
    output_path = make_fullpath(output_dir, make=True, enforce="directory")
    
    input_files = list(input_path.glob("*.png"))
    if not input_files:
        _LOGGER.warning(f"Input directory is empty: {input_path}")
        return
        
    _LOGGER.info(f"Found {len(input_files)} images in the input directory.")
    
    grouped_tasks = defaultdict(lambda: defaultdict(list))
    pattern = LABEL_STUDIO_PATTERN
    
    for file_path in input_files:
        match = pattern.match(file_path.name)
        if match:
            grouped_tasks[match.group(1)][match.group(2)].append(file_path)
    
    for base_task, grouped_masks in grouped_tasks.items():
        first_path = next(iter(grouped_masks.values()))[0]
        image_shape = Image.open(first_path).size[::-1] 
    
        merged_mask = np.zeros(image_shape, dtype=np.uint8)
        
        for label_name, paths in grouped_masks.items():
            if label_name not in class_map:
                _LOGGER.warning(f"Label '{label_name}' is not in the class_map. Skipping.")
                continue
                
            class_id = class_map[label_name]
            for path in paths:
                mask_array = np.array(Image.open(path).convert("L"))
                merged_mask[mask_array > 127] = class_id
                
        current_output_path = output_path / f"{base_task}.png"
        Image.fromarray(merged_mask).save(current_output_path)
        
    _LOGGER.info(f"Successfully saved {len(grouped_tasks)} merged output images.")


def merge_masks_with_inferred_class(
    input_dir: Union[Path, str], 
    output_dir: Union[Path, str], 
    class_map: dict[str, int], 
    inferred_class_name: str
) -> None:
    """
    Merges individual segmentation masks into a single image, initializing the base 
    canvas with an inferred class ID and carving out a specific background.
    
    The function uses a regular expression to parse filenames in the format 
    '<base_task>-tag-<label_name>[-<optional_index>].png'. 

    This function is designed for scenarios where the entire image should default to a 
    specific class (the inferred class), except for areas explicitly marked as 'Background' or other specific labels.
    It first fills the canvas with the inferred class ID, sets any areas defined in the 
    'Background' mask to 0 (black), and then applies the remaining label masks on top.

    Args:
        input_dir (Path | str): The directory containing the individual label mask PNG files 
            generated by the annotation tool.
        output_dir (Path | str): The directory where the final merged mask PNG files 
            will be saved. It will be created if it does not exist.
        class_map (dict[str, int]): A dictionary mapping the string label names 
            (parsed from the filenames) to their corresponding integer class IDs 
            (e.g., {"Background": 0, "Voids": 1}).
        inferred_class_name (str): The label name corresponding to the class that 
            should fill the initial canvas (must exist in the class_map).
    """
    if inferred_class_name not in class_map.keys():
        _LOGGER.error(f"Inferred class name '{inferred_class_name}' not found in class_map.")
        raise ValueError()
    
    input_path = make_fullpath(input_dir, make=False, enforce="directory")
    output_path = make_fullpath(output_dir, make=True, enforce="directory")
    
    input_files = list(input_path.glob("*.png"))
    if not input_files:
        _LOGGER.warning(f"Input directory is empty: {input_path}")
        return
        
    _LOGGER.info(f"Found {len(input_files)} images in the input directory.")
    
    grouped_tasks = defaultdict(lambda: defaultdict(list))
    pattern = LABEL_STUDIO_PATTERN
    
    for file_path in input_files:
        match = pattern.match(file_path.name)
        if match:
            grouped_tasks[match.group(1)][match.group(2)].append(file_path)
            
    for base_task, grouped_masks in grouped_tasks.items():
        bg_key = next((k for k in grouped_masks.keys() if k.lower() == "background"), None)
        if not bg_key:
            _LOGGER.error(f"No 'Background' label found for task '{base_task}'. A background mask is required to carve out the inferred class.")
            raise ValueError()

        first_path = next(iter(grouped_masks.values()))[0]
        image_shape = Image.open(first_path).size[::-1]
        
        inferred_class_id = class_map[inferred_class_name]
        merged_mask = np.full(image_shape, inferred_class_id, dtype=np.uint8)
        
        for path in grouped_masks[bg_key]:
            mask_array = np.array(Image.open(path).convert("L"))
            merged_mask[mask_array > 127] = 0
            
        for label_name, paths in grouped_masks.items():
            if label_name == bg_key:
                continue
            if label_name not in class_map:
                _LOGGER.warning(f"Label '{label_name}' not found in class_map. Skipping.")
                continue
                
            class_id = class_map[label_name]
            for path in paths:
                mask_array = np.array(Image.open(path).convert("L"))
                merged_mask[mask_array > 127] = class_id
                
        current_output_path = output_path / f"{base_task}.png"
        Image.fromarray(merged_mask).save(current_output_path)
        
    _LOGGER.info(f"Successfully saved {len(grouped_tasks)} merged output images.")
