import torch
from torch import nn
from typing import Literal

from .._core import get_logger
from ..keys._keys import MLTaskKeys, SchemaKeys
from ..schema import FeatureSchema
from ..ML_models._base_save_load import _ArchitectureBuilder

_LOGGER = get_logger("Sequence LSTM")


__all__ = [
    "DragonSequenceLSTM"
]


class DragonSequenceLSTM(_ArchitectureBuilder):
    """
    An LSTM-based network for multivariate sequence prediction tasks.
    
    Dynamically constructs separate prediction heads for continuous and categorical 
    targets based on the provided FeatureSchema.
    """
    def __init__(self, 
                 schema: FeatureSchema,
                 targets: list[str],
                 prediction_mode: Literal["sequence-to-sequence", "sequence-to-value"],
                 sequence_length: int,
                 hidden_size: int = 100,
                 recurrent_layers: int = 2,
                 dropout: float = 0.1,
                 bidirectional: bool = False):
        """
        Initializes the multi-head LSTM for multivariate sequence prediction.

        Args:
            schema (FeatureSchema): The definitive schema containing feature names, data types, 
                and categorical cardinality configurations.
            targets (list[str]): A list of column names indicating the target variables to predict.
            prediction_mode (str): Determines the temporal structure of the outputs.
                - 'sequence-to-sequence': Predicts a full sequence matching the input time steps.
                - 'sequence-to-value': Predicts single values corresponding to the final time step.
            sequence_length (int): The exact length of the sliding windows generated by the dataset.
            hidden_size (int): The number of features in the LSTM's hidden state
            recurrent_layers (int): The number of recurrent LSTM layers.
            dropout (float): The dropout probability for all but the last LSTM layer.
            bidirectional (bool): If True, becomes a bidirectional LSTM.
        """
        super().__init__()

        # --- 1. Validation ---
        if prediction_mode not in [MLTaskKeys.SEQUENCE_SEQUENCE, MLTaskKeys.SEQUENCE_VALUE]:
            _LOGGER.error(f"Unrecognized prediction mode: '{prediction_mode}'.")
            raise ValueError()
            
        if not targets:
            _LOGGER.error("The 'targets' list cannot be empty.")
            raise ValueError()

        if not isinstance(hidden_size, int) or hidden_size < 1:
            _LOGGER.error("hidden_size must be a positive integer.")
            raise ValueError()

        if not isinstance(recurrent_layers, int) or recurrent_layers < 1:
            _LOGGER.error("recurrent_layers must be a positive integer.")
            raise ValueError()

        if not (0.0 <= dropout < 1.0):
            _LOGGER.error("dropout must be a float between 0.0 and 1.0.")
            raise ValueError()

        # --- 2. Save configuration for _ArchitectureBuilder ---
        self.model_hparams = {
            SchemaKeys.SCHEMA_DICT: schema.to_dict(),
            'targets': targets,
            'prediction_mode': prediction_mode,
            'sequence_length': sequence_length,
            'hidden_size': hidden_size,
            'recurrent_layers': recurrent_layers,
            'dropout': dropout,
            'bidirectional': bidirectional
        }

        self.prediction_mode = prediction_mode
        self.targets = targets
        self.sequence_length = sequence_length
        self.in_features = schema.number_of_features
        self.hidden_size = hidden_size
        self.recurrent_layers = recurrent_layers
        self.dropout = dropout
        self.bidirectional = bidirectional

        # --- 3. LSTM Backbone ---
        self.lstm = nn.LSTM(
            input_size=self.in_features,
            hidden_size=hidden_size,
            num_layers=recurrent_layers,
            dropout=dropout if recurrent_layers > 1 else 0.0,
            bidirectional=bidirectional,
            batch_first=True  # Crucial for (batch, seq, feature) inputs
        )
        
        # Calculate dimension feeding into head projections
        head_in_features = hidden_size * 2 if bidirectional else hidden_size

        # --- 4. Multi-Head Outputs ---
        # Generate distinct heads for each target based on its data type
        self.target_heads = nn.ModuleDict()

        for target in targets:
            if target in schema.categorical_feature_names:
                target_idx = schema.feature_names.index(target)
                if schema.categorical_index_map and target_idx in schema.categorical_index_map:
                    cardinality = schema.categorical_index_map[target_idx]
                else:
                    _LOGGER.warning(f"Cardinality for categorical target '{target}' not found. Defaulting to 2.")
                    cardinality = 2

                self.target_heads[target] = nn.Linear(head_in_features, cardinality)
            else:
                self.target_heads[target] = nn.Linear(head_in_features, 1)

    def forward(self, x: torch.Tensor) -> dict[str, torch.Tensor]:
        """
        Defines the forward pass.

        Args:
            x (torch.Tensor): Input tensor of shape (batch_size, sequence_length, features)
                              or (batch_size, sequence_length).

        Returns:
            dict[str, torch.Tensor]: A dictionary mapping each target name to its prediction tensor.
        """
        # --- Handle Input Shape ---
        if x.ndim == 2:
            x = x.unsqueeze(-1)

        # lstm_out shape: (batch_size, seq_len, hidden_size * num_directions)
        lstm_out, _ = self.lstm(x)

        # --- Route through Multi-Heads ---
        predictions = {}

        if self.prediction_mode == MLTaskKeys.SEQUENCE_VALUE:
            # Isolate the final time step: (batch_size, head_in_features)
            last_step = lstm_out[:, -1, :]

            for target_name, head in self.target_heads.items():
                out = head(last_step)
                # Squeeze the feature dim ONLY if it's a single continuous target
                predictions[target_name] = out.squeeze(-1) if out.shape[-1] == 1 else out

        elif self.prediction_mode == MLTaskKeys.SEQUENCE_SEQUENCE:
            for target_name, head in self.target_heads.items():
                out = head(lstm_out)
                # Squeeze the feature dim ONLY if it's a single continuous target
                predictions[target_name] = out.squeeze(-1) if out.shape[-1] == 1 else out

        return predictions

    def get_architecture_config(self) -> dict:
        """Returns the configuration of the model for serialization."""
        return self.model_hparams
