import math
import torch
from torch import nn
from typing import Literal

from .._core import get_logger
from ..keys._keys import MLTaskKeys, SchemaKeys
from ..schema import FeatureSchema
from ..ML_models._base_save_load import _ArchitectureBuilder

_LOGGER = get_logger("Sequence Transformer")


__all__ = [
    "DragonSequenceTransformer"
]


class PositionalEncoding(nn.Module):
    """Injects positional information into the sequence embeddings."""
    def __init__(self, d_model: int, dropout: float = 0.1, max_len: int = 1000):
        super().__init__()
        self.dropout = nn.Dropout(p=dropout)

        position = torch.arange(max_len).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, d_model, 2) * (-math.log(10000.0) / d_model))
        pe = torch.zeros(1, max_len, d_model)
        pe[0, :, 0::2] = torch.sin(position * div_term)
        pe[0, :, 1::2] = torch.cos(position * div_term)
        self.register_buffer('pe', pe)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # x shape: (batch_size, seq_len, d_model)
        x = x + self.pe[:, :x.size(1), :] # type: ignore # self.pe is a buffer
        return self.dropout(x)


class DragonSequenceTransformer(_ArchitectureBuilder):
    """
    A Transformer-based network for multivariate sequence prediction tasks.
    
    Dynamically generates separate prediction heads for continuous and categorical 
    targets based on the provided FeatureSchema.
    """
    def __init__(self, 
                 schema: FeatureSchema,
                 targets: list[str],
                 prediction_mode: Literal["sequence-to-sequence", "sequence-to-value"],
                 sequence_length: int,
                 d_model: int = 128,
                 nhead: int = 4,
                 num_layers: int = 3,
                 dim_feedforward: int = 512,
                 dropout: float = 0.1):
        """
        Initializes the multi-head Transformer for multivariate sequence prediction.
    
        This architecture dynamically constructs distinct output heads for each target based on 
        its data type (continuous vs. categorical) as defined in the provided FeatureSchema. 
        To maximize memory efficiency, positional encoding buffers are tightly bound to the 
        exact sequence length expected from the dataset windows.
        
        Args:
            schema (FeatureSchema): The definitive schema containing feature names, data types, 
                and categorical cardinality configurations.
            targets (list[str]): A list of column names indicating the target variables to predict.
            prediction_mode (str): Determines the temporal structure of the outputs.
                - 'sequence-to-sequence': Predicts a full sequence matching the input time steps.
                - 'sequence-to-value': Predicts single values corresponding to the final time step.
            sequence_length (int): The exact length of the sliding windows generated by the dataset. 
                Used to optimally allocate the pre-computed positional encoding buffer.
            d_model (int): The number of expected features in the encoder inputs (embedding dimension). 
            nhead (int): The number of heads in the multi-head attention models. Should evenly divide `d_model`.
            num_layers (int): The number of sub-encoder layers in the Transformer. 
            dim_feedforward (int): The dimension of the feedforward network model within the encoder. 
            dropout (float): The dropout probability applied to the encoder layers and positional encodings.
        """
        super().__init__()

        # --- 1. Validation ---
        if prediction_mode not in [MLTaskKeys.SEQUENCE_SEQUENCE, MLTaskKeys.SEQUENCE_VALUE]:
            _LOGGER.error(f"Unrecognized prediction mode: '{prediction_mode}'.")
            raise ValueError()
            
        if not targets:
            _LOGGER.error("The 'targets' list cannot be empty.")
            raise ValueError()

        # --- 2. Save configuration for _ArchitectureBuilder ---
        self.model_hparams = {
            SchemaKeys.SCHEMA_DICT: schema.to_dict(),
            'targets': targets,
            'prediction_mode': prediction_mode,
            'sequence_length': sequence_length,
            'd_model': d_model,
            'nhead': nhead,
            'num_layers': num_layers,
            'dim_feedforward': dim_feedforward,
            'dropout': dropout,
        }
        
        self.prediction_mode = prediction_mode
        self.targets = targets
        self.sequence_length = sequence_length
        self.in_features = schema.number_of_features

        # --- 3. Transformer Backbone ---
        self.input_projection = nn.Linear(self.in_features, d_model)
        self.pos_encoder = PositionalEncoding(d_model, dropout, max_len=sequence_length)
        
        encoder_layers = nn.TransformerEncoderLayer(
            d_model=d_model, 
            nhead=nhead, 
            dim_feedforward=dim_feedforward, 
            dropout=dropout,
            batch_first=True  # Crucial for (batch, seq, feature) inputs
        )
        self.transformer_encoder = nn.TransformerEncoder(encoder_layers, num_layers=num_layers)

        # --- 4. Multi-Head Outputs ---
        # Generate distinct heads for each target based on its data type
        self.target_heads = nn.ModuleDict()
        
        for target in targets:
            if target in schema.categorical_feature_names:
                # Retrieve the cardinality (number of classes) for cross-entropy logits
                target_idx = schema.feature_names.index(target)
                if schema.categorical_index_map and target_idx in schema.categorical_index_map:
                    cardinality = schema.categorical_index_map[target_idx]
                else:
                    _LOGGER.warning(f"Cardinality for categorical target '{target}' not found. Defaulting to 2.")
                    cardinality = 2
                
                # Head outputs raw logits mapping to the number of classes
                self.target_heads[target] = nn.Linear(d_model, cardinality)
            else:
                # Head outputs a single continuous regression value
                self.target_heads[target] = nn.Linear(d_model, 1)

    def forward(self, x: torch.Tensor, is_causal: bool = False) -> dict[str, torch.Tensor]:
        """
        Defines the forward pass.

        Args:
            x (torch.Tensor): Input tensor of shape (batch_size, sequence_length, features)
            is_causal (bool): Whether to apply an autoregressive causal mask.

        Returns:
            dict[str, torch.Tensor]: A dictionary mapping each target name to its prediction tensor.
        """
        # --- Handle Input Shape ---
        if x.ndim == 2:
            x = x.unsqueeze(-1)
            
        seq_len = x.size(1)

        # 1. Project and encode positions
        x = self.input_projection(x)
        x = self.pos_encoder(x)

        # 2. Apply causal mask if required (standard for autoregressive Seq2Seq)
        mask = nn.Transformer.generate_square_subsequent_mask(seq_len, device=x.device) if is_causal else None

        # 3. Transformer Encode
        # shape: (batch_size, seq_len, d_model)
        memory = self.transformer_encoder(x, mask=mask)

        # 4. Route through Multi-Heads
        predictions = {}
        
        if self.prediction_mode == MLTaskKeys.SEQUENCE_VALUE:
            # Isolate the final time step: (batch_size, d_model)
            last_step = memory[:, -1, :]
            
            for target_name, head in self.target_heads.items():
                out = head(last_step)
                # Squeeze the feature dim ONLY if it's a single continuous target
                predictions[target_name] = out.squeeze(-1) if out.shape[-1] == 1 else out
                
        elif self.prediction_mode == MLTaskKeys.SEQUENCE_SEQUENCE:
            for target_name, head in self.target_heads.items():
                out = head(memory)
                # Squeeze the feature dim ONLY if it's a single continuous target
                predictions[target_name] = out.squeeze(-1) if out.shape[-1] == 1 else out

        return predictions
    
    def get_architecture_config(self) -> dict:
        """Returns the configuration of the model for serialization."""
        return self.model_hparams
